#1. Using range() function
r1 = 0 #range 1
r2 = 10 #range 2
li = list(range(r1,r2)) #initializing a list with the given range
print(li)

#using list comprehension()
r1 = 10
r2 = 20
li = [i for i in range(r1, r2)] #list comprehension iterates through a sequence of numbers generated by range(r1, r2), which starts at r1 and ends at r2 .
print(li)

#using numpy function
import numpy as np
r1 = 0
r2 = 10
li = np.arange(r1,r2).tolist()
print(li)